[package]
name = "prog3"
version = "1.0.0"
authors = ["Kimmo Matias Vuori Liikaluoma <vuoriliikaluoma@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
md5 = "0.7.0"
